BDC-2968 택시 배차 백엔드 API 구현
travelingaries/taxi-dispatch-backend-api pull request #1
Opened 2022-09-21 02:48 UTC by travelingaries

# 작업 내용 (Content)
- 택시 배차 시스템의 백엔드를 Ruby on Rails로 구현을 해보았습니다.

# 링크 (Links)
- [BDC-2968](https://dramancompany.atlassian.net/browse/BDC-2968)
- [스펙 문서](https://dramancompany.atlassian.net/wiki/spaces/API/pages/3792207992/api)
- [기획 문서](https://dramancompany.atlassian.net/wiki/spaces/~6320305acd4a82cf977c6fa3/pages/27947532599/-+API)

# 기타 사항 (Etc)
n/a

# Merge 전 필요 작업 (Checklist before merge)
n/a

# 희망 리뷰 완료 일 (Expected due date)
n/a

2022-09-27 00:48 UTC, 51326 commented
사람마다 개발툴 설정이 다르기 때문에 개발툴 환경 설정 파일(.idea)은 저장소에 보통 제외시켜둡니다!
그리고 rubocop 실행시 받아지는 아래 파일도 제외시켜두는게 좋을 것 같네요.
`.rubocop-https---raw-githubusercontent-com-dramancompany-rubocop-drama-master--rubocop-drama-yml`

코드 리뷰도 오늘 중으로 진행해서 남겨두겠습니다!

2022-09-27 02:47 UTC, soolab reviewed
수고하셨습니다 준혁님! 커멘트 몇가지 달아두었습니다!

2022-09-27 02:47 UTC, soolab commented on app/models/user/driver.rb
> +end
is_a?를 사용하여 User가 Driver이냐 Passenger이냐를 구분하기 위해서 이렇게 코드를 작성하신걸로 이해하고 있는데요,
단순 구분이 목적이였다면 user에 type을 enum으로 두어서 구분하는게 더 적절하지 않을까 생각이 됩니다!

2022-09-27 02:47 UTC, soolab commented on app/controllers/taxi_requests_controller.rb
> +    raise ErrorLibrary::InvalidParameters if params[:address].length > 100
address 같은 경우 TaxiRequest의 property이라서 TaxiRequest Model에서 validate하는게 더 적절하다고 생각이 드네요!

2022-09-27 02:47 UTC, soolab commented on app/models/taxi_request.rb
> +end
status 같은 경우에 모델에서 enum으로 만들어주는게 더 좋을 것 같아요,
위에서도 where(status: 1) 과 같은 코드들이 보이는데 이렇게 되면은 어떤 숫자와 상태가 매핑되어있는지
개발자가 일일히 찾거나 외워야하는 상황인 것 같아서, where(status: :wating) 이런식으로 사용할 수 있게 되면 더 좋을 것 같아요!

2022-09-27 02:47 UTC, soolab commented on spec/factories/user.rb
> +    end
여기는 아무것도 하지 않아서 지워주면 될 것 같네요!

2022-09-27 02:47 UTC, soolab commented on spec/factories/user.rb
> +  factory :user, class: User::Passenger do
class 명은 User가 되어야하는게 맞지 않나요??
User는 Passenger도 될 수 있고 Driver도 될 수 있는 구조로 이해하고 있어서요!

2022-09-27 02:47 UTC, soolab commented on spec/controllers/users_controller_spec.rb
> +  end
```suggestion
  describe '#sign_in' do
    fixtures :users
    context '유효한 이메일과 패스워드인 경우' do
      it "HTTP STATUS 200을 응답한다" do
        post :sign_in, params: { email: "passenger1@dramancompany.com", password: "eiusmod" }
        expect(response).to have_http_status(200)
      end
    end
    
    context '유효하지 않은 이메일과 패스워드인 경우' do
      it "HTTP STATUS 400을 응답한다" do
        post :sign_in, params: { email: "drama@dramancompany.com", password: "eiusmod" }
        expect(response).to have_http_status(400)
      end
    end
  end
```

이건 저희가 사용하는 컨벤션인데요,
class method인 경우에는 '.method_name'
instance method인 경우에는 '#method_name' 으로 테스트하려는 메소드명을 적어주시면 됩니다!

그 다음으로는 context '~~한 경우' 로 케이스를 적어주시고
it '~~한다' 식으로 메세지를 적어주시면 될 것 같아요!

2022-09-27 03:01 UTC, travelingaries commented
> b55e727

[b55e727](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/b55e727139f76a7a7aa091a0fed1d7959e8f4851) 에서 `.rubocop-https-...-yml` 파일과 .idea 리포에서 제외했습니다 🙆‍♂️

2022-09-27 04:13 UTC, travelingaries commented on app/controllers/taxi_requests_controller.rb
> +    end
@soolab 앗 혹시 find_each가 batch_size 1000개 이상일 때 유용한 메소드인 이유 설명 요청드릴 수 있을까요?? 제가 아는 선에서는 batch_size가 너무 크면 그 개수만큼 한 번에 메모리에 로드하기 때문에 적당한 사이즈를 잘 찾는게 좋은 걸로 알고 있었어요. 사실 50는 굉장히 보수적인 사이즈라 더 늘려도 될 듯 하긴 한데, 클수록 좋을 다른 배경이 있을지도 궁금합니다~

2022-09-27 04:15 UTC, travelingaries commented on app/controllers/taxi_requests_controller.rb
> +    end
rubocop에서도 메소드 길이가 20 넘으면 안 된다고 경고주길래, 새 리팩토링 브랜치 파서 거기서 serializer 생성해볼게요🙆‍♂️ 설명 감사합니다

2022-09-27 04:17 UTC, travelingaries commented on app/controllers/taxi_requests_controller.rb
> +    request.save!
[a362272](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/a3622722c83401365f65e51d46b639837a76d135) 에서 수정했습니다 감사합니다~ suggestion 기능은 처음 보네요 😮

2022-09-27 04:18 UTC, soolab commented on app/controllers/taxi_requests_controller.rb
> +    end
Note: This method is only intended to use for batch processing of large amounts of records that wouldn’t fit in memory all at once. If you just need to loop over less than 1000 records, it’s probably better just to use the regular find methods.

클수록 좋다기보단 default batch_size가 1000이기도하고 문서에서도 그보다 적을시는 일반 find나 where를 쓰도록 권고하고 있네요.
그보다 작을시에는 쿼리 돌리는 횟수가 많아지니까 오히려 성능이 좋지 않다라고 생각할 수 있을 것 같아요!

2022-09-27 04:25 UTC, travelingaries commented on app/models/user/driver.rb
> +end
현재 스펙대로라면 사실 단순 구분만 필요한게 맞을 듯 한데, 일반적인 장기 프로젝트라 가정했을 때 Driver와 Passenger 모델마다 필요한 함수 구현, 콜백 등이 달라질 수 있겠다고 생각들어서 Class 분리해보았는데, 어느 정도까지 가정해야 할지 헷갈리네요 🤔 혹시 @51326 님도 요 부분에 대해 의견 요청드릴 수 있을까요?

2022-09-27 04:27 UTC, travelingaries commented on spec/factories/user.rb
> +    end
앗 요거 https://github.com/travelingaries/taxi-dispatch-backend-api/pull/2/files#diff-a12f3969d7a6c15cabc1fa42a2286fc3cf38bb7be9ae855ca8a59de85944b755 (다른 PR)에서 수정했는데 여기 빈 껍데기를 놔두었군요.. [BDC-2981 테스트코드 보완 및 리팩토링](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/2) PR에서 수정했습니다!

2022-09-27 04:29 UTC, travelingaries commented on spec/factories/user.rb
> +  factory :user, class: User::Passenger do
이 부분도 [BDC-2981 테스트코드 보완 및 리팩토링 PR](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/2/files#diff-a12f3969d7a6c15cabc1fa42a2286fc3cf38bb7be9ae855ca8a59de85944b755)에서 이어서 수정을 했는데, 제가 develop PR을 중간에 한 번에 올리느라 난잡하게 정리되어있네요 죄송합니다.. 🙏 테스트코드 PR에서 수정했습니다!

2022-09-27 04:32 UTC, travelingaries commented on spec/controllers/users_controller_spec.rb
> +  end
설명 감사합니다! 요거 여기 develop PR에서 말고 [테스트코드 PR](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/2)에서 작업해서 커밋 올리겠습니다 🙆‍♂️

2022-09-27 04:53 UTC, travelingaries commented on app/controllers/taxi_requests_controller.rb
> +    end
설명 감사합니다. 다만 `batch_size` 관련 부분은 제 생각에는 일반화하기엔 쉽지 않을 것 같긴 해요 🤔 
배치 사이즈가 너무 클 경우 모델들을 한 번에 불러오는 rails 특성 상 메모리 과부하가 있을 수도 있고 (예시: [스택오버플로우 관련 이슈](https://stackoverflow.com/a/35496316)), 특히 불러오는 모델이 여러 다른 모델들과 join되는 형태라면 쿼리가 여러 번 나가더라도 한 번에 메모리에 로드하는 개수를 조절하는게 좋은 것으로 알고 있긴 했었어요
혹시 @51326 이 부분에 대해서도 새 시각 요청드릴 수 있을까요?

2022-09-27 08:45 UTC, 51326 reviewed
의견 남겨두었습니다.
컨트롤러에 중복될 수 있는 의견에 대해서는 생략하였습니다.

테스트 코드도 따로 FactoryBot을 사용한 별도 PR이 있다고 하셔서 생략하였습니다.

2022-09-28 11:07 UTC, travelingaries commented
테스트코드 리팩토링 후 [테스트코드 PR](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/2) develop에 rebase and merge해두었습니다~ @51326 @soolab

2022-09-28 15:42 UTC, travelingaries commented on app/controllers/taxi_requests_controller.rb
> +    end
자세한 설명 감사합니다  🙇 
저도 기존에 주로 find_each를 배치 작업 돌릴 때 사용했고, pagination이 들어간다면 굳이 controller단에서 사용할 필요까지는 없다는 점은 동의해요
여기서는 스펙 상 pagination이 안 들어가니 많은 레코드를 불러오면서 메모리 과부하에 대비해 find_each를 써보겠다고 생각했던 거고,
기존에 association이 많이 걸린 모델들 ActiveRecord에 find_each를 걸 때 batch_size를 보수적으로 잡는 데에 익숙하다 보니
(예: `TvSeason.where(...).find_each` 에서 TvSeason은 TvSeries, TvEpisode, Translation, Localization, Comment, Rating, User, 그외 영상 스트림 관련 다양한 모델들 등에 association이 걸려 있어서, 다량의 TvSeason들을 로드하면 메모리를 크게 잡아먹을 수 있어서 주로 개수 제한을 걸었어요),
습관적(?)으로 batch_size를 낮춰 잡긴 했는데, 사실 현재 모델 정도로는 큰 이슈가 될 것이 아닌 게 맞을 듯 해요

find_each의 목적에 대해서는 이참에 저도 짚고 가겠습니다. 생각할 계기를 제공해주셔서 감사합니다 🙏 @soolab @51326

2022-09-28 15:44 UTC, travelingaries commented on app/controllers/taxi_requests_controller.rb
> +    end
이 부분에 대해서는 [ad39742](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/ad3974201f53e08b9a87ed624c56163a992b588f) 애서, find_each를 안 쓰도록 수정했고 serializer를 생성해서 컨트롤러를 정리해두었어요~
전 serializer를 active_record_serializer gem을 활용하는 거에 더 익숙해서 그렇게 구현해보았는데, 혹시 career-api 등에서 active_record_serializer를 안 쓰시는 이유가 따로 있다면 설명해주시면 감사해요 🙏

2022-09-28 15:51 UTC, travelingaries commented on app/models/user/driver.rb
> +end
요거 어제 일승님과 콜하면서 설명드렸는데,
rails에선 모델에 type attribute가 있고, 이 type 값을 `User::Passenger` 형태로 저장해두면 자동으로 User의 서브클래스인 Passenger와 매핑해주는 기능을 제공해요~
이를 활용하기 위해서 DB에도 enum이 아닌 type값을 `User::Passenger`, `User::Driver`로 저장하고 있었고, 서브클래스 파일들을 만들어놓지 않으면 호출 시 에러가 나기 때문에 빈 클래스로라도 만들어둔 상황이에요

이렇게 안 하고 enum으로 해도 구현이 가능한건 맞지만, enum대신 type 관련 기능들을 활용했을 때 편하게 구현할 수 있는 부분들이 많아서 (예시: [UserSerializer 일부](https://github.com/travelingaries/taxi-dispatch-backend-api/blob/ad3974201f53e08b9a87ed624c56163a992b588f/app/serializers/user_serializer.rb#L18-L25)), 일승님도 어제 설명 공유 후 enum으로 바꿀 필요는 없겠다고 얘기하셔서, 우선 유지하는 방향으로 갈게요 🙏

2022-09-28 15:52 UTC, travelingaries commented on spec/controllers/users_controller_spec.rb
> +  end
@soolab 테스트코드들 리팩토링 완료해서, 새로 리뷰해주시면 감사합니다!

2022-09-29 00:15 UTC, travelingaries commented on app/models/user/driver.rb
> +end
[Rails Single Table Inheritance(STI)](https://gist.github.com/oojikoo-gist/97ffcf9f73086d2be232) 내용 참고 부탁드릴게요!

2022-09-29 00:50 UTC, travelingaries commented on app/models/user.rb
> +require 'user/passenger'
Single Table Inheritance(STI) 사용 시 서브클래스들이 lazy loading되는데, 명시적으로 require를 해두지 않으면 User.descendants가 빈 배열이 뜨는 등 예상치 못한 이슈들이 생길 수 있어서 require해두었어요~
관련 내용:https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#single-table-inheritance

2022-09-29 03:58 UTC, travelingaries commented on app/models/user/driver.rb
> +end
[여기 미디엄 글](https://medium.com/@GeneHFang/single-table-inheritance-in-rails-6-emulating-oop-principles-in-relational-databases-be60c84e0126)에 쉽게 설명이 되어있어서 같이 공유드려요~

2022-09-29 06:10 UTC, travelingaries commented on app/controllers/taxi_requests_controller.rb
> +  end
@soolab @51326 ApplicationController에서 에러 타입별로 rescue_from하도록 [90bbd72](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/90bbd729142761c8f3205941a874867f157745c6) 에서 수정했습니다, 감사합니다!

2022-09-29 06:11 UTC, travelingaries commented on app/controllers/taxi_requests_controller.rb
> +    param! :address, String, required: true
[90bbd72](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/90bbd729142761c8f3205941a874867f157745c6) 에서 (ApplicationController에서 에러 핸들링하도록 수정하면서) 같이 Strong parameter 사용하도록 작업했습니다, 설명 감사합니다~

2022-09-29 06:12 UTC, travelingaries commented on app/controllers/taxi_requests_controller.rb
> +    raise ErrorLibrary::InvalidParameters if params[:address].length > 100
[90bbd72](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/90bbd729142761c8f3205941a874867f157745c6) 에서 (ApplicationController에서 에러 핸들링 + Strong parameter 사용 작업하면서 같이) address 길이 체크를 model에서 하도록 수정했습니다~

2022-09-29 07:18 UTC, travelingaries commented on app/models/user/driver.rb
> +end
추가로 [06b0555](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/06b055595678e1a119c69ebbf2d04d16f62682aa) 에서 User, TaxiRequests 사이의 association을 변경하면서, `User::Driver`, `User::Passenger`로 has_many association을 옮겨두었어요~

2022-09-29 08:17 UTC, travelingaries commented on app/models/taxi_request.rb
> +end
User, TaxiRequest의 status를 [1d7fd29](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/1d7fd295bf56d204e864187db2bdbabf7a17b3a9)에서 enum으로 변경했습니다~

2022-09-29 08:22 UTC, travelingaries commented on app/services/current_user_provider.rb
> +  end
Thread.current 이슈와 헷갈렸는데, after_action 불필요한게 맞아서 [395714f](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/395714fa2a8a7a28b7e1802572df2a40325fef1e)에서 제거했습니다 🙆‍♂️

2022-09-29 08:30 UTC, travelingaries commented on app/services/current_oauth.rb
> +    !token.nil? && token[:jwt]
[ef6db85](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/ef6db85287fa6b6220086b4b6f66e875ce6e23b0)에서 알려주신 authenticate_with_http_token 사용하도록 수정했습니다 🙇

2022-09-29 08:31 UTC, travelingaries commented on app/controllers/users_controller.rb
> +    user = log_in_user(user)
[5050043](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/5050043d3cf5a86cd45147a6b5d46836582da617)에서 설명해주신 대로 수정했습니다 🙏

2022-09-29 15:33 UTC, soolab reviewed
고생하셨습니다  준혁님! 😄
커멘트 몇가지 달아두었습니다. 이전처럼 의문인점이나 궁금하신점을 적극적으로 달아주세요!
저또한 일승님의 더 꼼꼼한 리뷰를 기다리며..

2022-09-29 15:33 UTC, soolab commented on spec/controllers/taxi_requests_controller_spec.rb
> +        end
응답의 길이가 1인것 뿐만 아니라, 응답된 taxi_request의 passenger_id가 요청한 passender의 id와 동일한지도 expect로 확인하셔야 할 것 같아요!

2022-09-29 15:33 UTC, soolab commented on spec/controllers/taxi_requests_controller_spec.rb
> +  context '유효한 토큰이 있는 기사인 경우' do
context 별로 다시 method들을 테스트 하셨는데, 이것도 물론 유효한 방법입니다!
하지만 저희 컨벤션은 describe '#method'를 최상단에 두고, 그 하위에 context를 통해 모든 케이스들을 테스트하는게 보통이라는 점은 알아두시면 나중에 다른 개발자분들이 리뷰하기 좋을 것 같다는 생각이 듭니다!

2022-09-29 15:33 UTC, soolab commented on spec/controllers/taxi_requests_controller_spec.rb
> +    fixtures :taxi_requests
저는 개인적으로 fixtures를 사용하지 않고 factory bot만 사용해서 이 방법에 대해서는 제가 정확히 잘 모르겠지만
얼필 추측하자면, fixture 하위에 있는 yml를 통해서 데이터를 생성하는 것 처럼 보이네요

데이터를 생성하는 것 또한 taxi_request factory bot의 create_list 를 이용하면 쉽게 여러개의 데이터를 한번에 생성할 수 있어서 그 방법으로 구현해보는건 어떨까 싶습니다!

2022-09-29 15:33 UTC, soolab commented on spec/controllers/taxi_requests_controller_spec.rb
> +        end
이것도 응답의 길이가 4인것 뿐만 아니라 driver_id가 nil이거나 해당 driver_id가 맞는지 확인하는 테스트가 필요해보입니다.
(요구조건이 이게 맞나요..? 택시 API 요구조건이 정확히 기억이 안나서 ㅎㅎ..)

2022-09-29 15:33 UTC, soolab commented on spec/controllers/taxi_requests_controller_spec.rb
> +      let!(:taxi_request) { create(:taxi_request, passenger_id: passenger.id) }
```suggestion
      let!(:taxi_request) { create(:taxi_request, passenger: passenger) }
```
id로 하셔도 되지만 이렇게 사용해도 무방합니다!

2022-09-29 15:33 UTC, soolab commented on spec/controllers/taxi_requests_controller_spec.rb
> +        end
```suggestion
        before(:each) { taxi_request.update!(driver: another_driver) }
```
이렇게 하면 한줄로 코드를 적을 수 있을 것 같아요!

2022-09-29 15:33 UTC, soolab commented on spec/controllers/taxi_requests_controller_spec.rb
> +        before(:each) do
이제와서 적는건데 (:each)없이 before 만 적어도 동일하게 동작하지 않나요?

2022-09-29 15:33 UTC, soolab commented on spec/controllers/users_controller_spec.rb
> +    let(:params) { { email: email, password: password, userType: 'passenger' } }
params에서도 snake 형식으로 user_type이 더 적절해보입니다!

2022-09-29 15:33 UTC, soolab commented on spec/controllers/users_controller_spec.rb
> +        expect(subject['accessToken']).to_not be_nil
응답된 토큰값이 nil인것 뿐만 아니라 실제 토큰 값과 비교하면 더 좋을 것 같아요.

2022-09-29 15:33 UTC, soolab commented on spec/factories/taxi_request.rb
> +    driver_id         {  }
driver_id 또는 driver를 미리 지정하지 않고 싶을 경우에는 제거하셔도 무방합니다.
dummy data가 필요한 property만 지정하셔도 될 것 같아요.
그 대신 생성할때 create(:taxi_request, driver: driver) 처럼 지정은 해주셔야 합니다.
(물론 driver값을 넣고 싶거나, driver가 required라면요)

2022-09-29 15:33 UTC, soolab commented on spec/fixtures/taxi_requests.yml
> +taxi_request_waiting_1:
위에도 적었는데 이렇게 fixture를 사용하기보단 factory bot으로 대체하는게 더 좋아보이네요!

2022-09-29 15:33 UTC, soolab commented on spec/controllers/users_controller_spec.rb
> +      end
여기도 nil인것 뿐만 아니라 해당 생성된 id가 맞는지 체크해보는게 좋을 것 같아요.

2022-09-30 08:10 UTC, travelingaries commented on app/controllers/taxi_requests_controller.rb
> +    raise ErrorLibrary::Forbidden if current_user.is_a?(User::Passenger)
[331ec93](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/331ec932d871359524dae3b04f20af619517d9a8)에서 UserTypeResolver라는 concern 새로 만들어두었어요 🙆‍♂️

2022-09-30 08:12 UTC, travelingaries commented on app/controllers/application_controller.rb
> +  end
요거 career-api의 ApplicationController에서 이 순서로 되어있길래 동일하게 가져와봤습니다! 실제 로직들중에서 발생시키는 커스텀 에러들은 `Exceptions`고 (마지막에 s), 그외 `Exception`을 잡아내는 부분이라 별개로 운영되더라고요

2022-09-30 08:59 UTC, travelingaries commented on app/controllers/taxi_requests_controller.rb
> +    prev_request = TaxiRequest.where(passenger_id: current_user.id).order(created_at: :desc).first
진수님이 집어주신 것처럼 PK타는게 더 빠를 듯 해서 [149dba3](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/149dba3cae7650d4241ce21e319f9637134a032b)에서 id desc로 수정했습니다~

2022-09-30 09:00 UTC, travelingaries commented on app/controllers/users_controller.rb
> +  end
앗 [dabd469](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/dabd46919cc81191d36927a44a8265b86cbdaaf4)에서 수정했습니다 🙆‍♂️

2022-09-30 09:06 UTC, travelingaries commented on app/controllers/users_controller.rb
> +  end
요거는 스펙에서 camelCase로 전송이 되는걸 가정하도록 규정이 되어있었길래 우선 이렇게 해보았어요 🥲 (혹시 말하신 부분이 이게 아니라면 알려주세요)
<img width="395" alt="image" src="https://user-images.githubusercontent.com/19482142/193234876-caf02a6a-63cb-4b34-a00a-25607de3c15d.png">

이전에는 Rails API단에서는 전부 snake case로 내리고 받고, 웹 프론트 단에서 snake_case로 내려오는 응답들을 camelCase로 전환해서 사용하도록 미들웨어가 붙어있었는데, 그런 상황이 되면 이상적일 것 같네요!

2022-09-30 09:10 UTC, travelingaries commented on app/controllers/users_controller.rb
> +    end
이 리뷰 보기 전에 저 로직 [d01e7a7](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/d01e7a7ed1909b6a60afb80436d3629024e989c5)에서 살짝 수정했는데,
얘기해주신 것처럼 바로 리턴하는게 더 스펙에 맞을 듯 해서 [0c618d7](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/0c618d732e16cdd7547cd9e79f66c58849ce5017)에서 수정했습니다~

2022-09-30 09:11 UTC, travelingaries commented on spec/controllers/users_controller_spec.rb
> +    let(:params) { { email: email, password: password, userType: 'passenger' } }
요것도 위에서처럼, 스펙에서 userType으로 전달되는 상황을 가정하도록 하더라고요 😢

2022-09-30 09:13 UTC, travelingaries commented on spec/factories/taxi_request.rb
> +    driver_id         {  }
[1b742f0](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/1b742f0a16609672adae627fac5d0761a60e1ac5) 에서 줄 자체를 제거했습니다 🙆‍♂️

2022-10-04 00:44 UTC, travelingaries commented on app/controllers/taxi_requests_controller.rb
> +  end
제안주신 내용 참고해서 [68c50cc](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/68c50cc863c8d72e79bcbed6a35c642fa837aae1) 에서 수정했습니다 🙆‍♂️

2022-10-04 00:48 UTC, travelingaries commented on app/controllers/taxi_requests_controller.rb
> +    request = TaxiRequest.find_by(id: params[:taxi_request_id])
[90bbd72](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/90bbd729142761c8f3205941a874867f157745c6) 에서 strong parameter 사용하도록 수정했습니다

2022-10-04 00:50 UTC, travelingaries commented on app/controllers/taxi_requests_controller.rb
> +    raise ErrorLibrary::Duplicated if request.driver_id.present?
[여기](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1#discussion_r980766427)에서 제안주신 내용 참고해서 [68c50cc](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/68c50cc863c8d72e79bcbed6a35c642fa837aae1)에서 수정했습니다 🙆‍♂️

2022-10-04 00:51 UTC, travelingaries commented on app/controllers/taxi_requests_controller.rb
> +    request.update!(driver_id: current_user.id, accepted_at: Time.current)
[68c50cc](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/68c50cc863c8d72e79bcbed6a35c642fa837aae1) 작업하면서 같이 추가해두었습니다 🙆

2022-10-04 00:52 UTC, travelingaries commented on app/controllers/taxi_requests_controller.rb
> +    }
[ad39742](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/ad3974201f53e08b9a87ed624c56163a992b588f) 에서 active_record_serializer gem 사용해서 serializer 구현했습니다

2022-10-04 01:01 UTC, travelingaries commented on app/controllers/users_controller.rb
> +    return user_type.in?(%w[passenger driver])
[05526a2](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/05526a2fc1597370d3eba38ac6e83b1487e490a2)에서 상수로 수정했어요 🙆‍♂️
`%w[]`도 되긴 하는데 Rubocop에서 offense로 규정해서 [da71d7b](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/da71d7bcb532c0cb17e40c0706ba9017e8cf6c3b)에서 `%w()`로 수정했어요~

2022-10-04 01:09 UTC, travelingaries commented on app/serializers/taxi_request_serializer.rb
> +  end
[상단의 attributes](https://github.com/travelingaries/taxi-dispatch-backend-api/blob/05526a2fc1597370d3eba38ac6e83b1487e490a2/app/serializers/taxi_request_serializer.rb#L4-L4)에 정의된 항목들이 serialize했을 때 json의 key값들이 되는데, 각 attribute를 불렀을 때 어떤 값이 value에 해당할지 메소드로 정의가 되어있어야 하는 플로우에요
(참고로 [여기](https://github.com/travelingaries/taxi-dispatch-backend-api/blob/05526a2fc1597370d3eba38ac6e83b1487e490a2/app/serializers/taxi_request_serializer.rb#L13-L13)서 object는 [serializer를 부를 때](https://github.com/travelingaries/taxi-dispatch-backend-api/blob/05526a2fc1597370d3eba38ac6e83b1487e490a2/app/controllers/taxi_requests_controller.rb#L42-L42) 지정한 객체에요)

코드에 중복이 꽤 있던 상태라, [이 파일](https://github.com/travelingaries/taxi-dispatch-backend-api/blob/develop/app/serializers/taxi_request_serializer.rb)에서처럼 수정했어요!

2022-10-04 02:43 UTC, travelingaries commented on spec/controllers/application_controller_spec.rb
> +        end
앗 평소에 Timecop을 block으로만 활용했어서 놓쳤네요, 감사합니다!
[7c4c33b](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/7c4c33be3c4948f0ae499618c969341ccb2f798e) 에서 수정했습니다~

2022-10-04 02:49 UTC, travelingaries commented on spec/controllers/taxi_requests_controller_spec.rb
> +      passenger.save!
[12eca25](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/12eca25757e38fb6b7261fb4a7616a2399a4cc1f) 에서 수정했습니다 🙆‍♂️

2022-10-04 02:53 UTC, travelingaries commented on spec/controllers/taxi_requests_controller_spec.rb
> +  context '유효한 토큰이 있는 기사인 경우' do
앗 `#index`, `#create`, `#accept_request` 세 메소드에 걸쳐서 선 처리 작업들이 겹쳐보여서 이렇게 정리해보았는데, 그래도 describe가 최상위로 가는 군요
기억해두고 참고하겠습니다~ 🙏

2022-10-04 04:12 UTC, travelingaries commented on spec/controllers/taxi_requests_controller_spec.rb
> +        end
[bd43df8](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/bd43df8d0aee2a944f253c61d1ef09848332711d) 에서 해당 체크 추가했습니다 🙆‍♂️

2022-10-04 04:23 UTC, travelingaries commented on spec/controllers/taxi_requests_controller_spec.rb
> +    fixtures :taxi_requests
네 fixtures/taxi_requests.yml에 적은 내용들로 테스트 인스턴스들을 생성하는게 맞아요 🙆‍♂️ 
[3a48027](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/3a48027a60581777ac5edefba790c2dd2e57320a)에서 FactoryBot만 사용하도록 수정했습니다~

2022-10-04 04:28 UTC, travelingaries commented on spec/controllers/taxi_requests_controller_spec.rb
> +        end
index관련 요구 조건은
- 승객이라면 자신의 배차 요청들만 볼 수 있도록
- 기사라면 모든 배차 요청들을 볼 수 있도록
이라, 여기 테스트코드에선 driver_id 관련 조건은 없어도 괜찮다고 생각이 들었는데, 혹시 그래도 넣는게 낫겠다면 알려주세요 🙏 

(굳이 찾아보실 필요는 없지만) 혹시라도 요구 조건을 찾아보시는게 편하시다면 [과제 안내 문서](https://drive.google.com/drive/u/1/folders/1gbQbpdtkYxyc2Boc6X3cU025WPgPh08K) 또는 [기획 문서](https://dramancompany.atlassian.net/wiki/spaces/~6320305acd4a82cf977c6fa3/pages/27947532599/-+API)에서 확인해보실 수 있어요~

2022-10-04 04:30 UTC, travelingaries commented on spec/controllers/taxi_requests_controller_spec.rb
> +      let!(:taxi_request) { create(:taxi_request, passenger_id: passenger.id) }
[3d51fc0](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/3d51fc06cb4793708ceaa0e589762cfdc7c4d003) 에서 관련 부분들 같이 수정했습니다~

2022-10-04 04:34 UTC, travelingaries commented on spec/fixtures/taxi_requests.yml
> +taxi_request_waiting_1:
[3a48027](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/3a48027a60581777ac5edefba790c2dd2e57320a)에서 fixtures 안 사용하도록 수정했습니다~

2022-10-04 04:53 UTC, travelingaries commented on spec/controllers/taxi_requests_controller_spec.rb
> +        end
[74850f6](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/74850f68f0e3f8b9245c94c64557e57124861a7b)에서 제안주신 방법대로 커밋했습니다~

2022-10-04 04:54 UTC, travelingaries commented on spec/controllers/taxi_requests_controller_spec.rb
> +        before(:each) do
네 맞아요, before만 적어도 before(:each)와 동일해요 🙆‍♂️
`before(:each)`가 좀 더 명시적이라고 생각해서 그렇게 적었는데, `before`로 적는게 나을까요?

2022-10-04 05:30 UTC, travelingaries commented on spec/controllers/users_controller_spec.rb
> +        expect(subject['accessToken']).to_not be_nil
[30b39ed](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/30b39ed44764ededc26226f800f26033d69d19d5)에서 실제 토큰값과도 비교하도록 추가했습니다 🙆‍♂️

2022-10-04 05:34 UTC, travelingaries commented on spec/controllers/users_controller_spec.rb
> +      end
[71c2a6a](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/71c2a6a9b928aa92b5706436d57ed461b251d39f)에서 생성된 id도 같이 체크하도록 수정했습니다~

2022-10-04 08:29 UTC, travelingaries commented
@51326 생성 응답들 [095dc0e](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/095dc0ef321ccc8036d73605b78f82717fb735e2)에서 200 -> 201로 수정했습니다~

2022-10-05 01:11 UTC, soolab commented on spec/controllers/taxi_requests_controller_spec.rb
> +        before(:each) do
동일하게 동작한다면 굳이 안적어줘도 될 것 같고, 기존 테스트코드들에서도 적고있진 않아요 ㅎㅎ
생략해주셔도 될 것 같습니다~

2022-10-05 04:58 UTC, 51326 requested changes
리뷰가 길어져서 구현 코드 리뷰와 테스트 코드 리뷰 분리해서 submit 해둘게요!

2022-10-05 04:58 UTC, 51326 commented on app/controllers/users_controller.rb
> +    raise Exceptions::BadRequest, '올바른 사용자 타입을 입력해주세요' unless valid_user_type?(params[:userType])
저희는 xxx_params 메소드에서는 필수 파라미터에 대한 확인만 하고 있습니다.

파라미터 값에 대한 validation은 별도 메소드로 분리하거나 모델에서 해주세요!
email 값에 대한 유효성 검사는 model에서 해주는게 좋을 것 같습니다.

참고: https://github.com/dramancompany/career-api/blob/7e6aa8580a8e652d78739228ce460c25fa8a6316/app/models/recruiter.rb#L27

2022-10-05 04:58 UTC, 51326 commented on app/controllers/users_controller.rb
> +  end
if / else 보다는 가드문을 권장하고 사용하고 있습니다.
그리고 ParameterMissing에 대한 exception인 경우 파라미터가 누락된 경우 발생하는데 여기서는 아래 valid_xxx가 의미가 없는것 같네요.. 값에 대한 유효성 검사는 별도 메소드로 분리해주는게 좋을 것 같아요.

```suggestion
    raise Exceptions::BadRequest, '올바른 비밀번호를 입력해주세요' if params[:password].blank?
  end
    
  def sign_up_validate
    raise Exceptions::BadRequest, '올바른 이메일을 입력해주세요' unless valid_email?(params[:email])
    raise Exceptions::BadRequest, '올바른 사용자 타입을 입력해주세요' unless valid_user_type?(params[:userType])
  end
```

2022-10-05 04:58 UTC, 51326 commented on app/controllers/users_controller.rb
> +    raise Exceptions::Conflict, '이미 가입된 이메일입니다' if User.find_by(email: params[:email]).present?
값에 대한 존재 유무를 검색할땐 exists? 메소드를 사용해주세요.
그리고 이 validation은 User 모델에 있는게 좋을 것 같아요.
https://guides.rubyonrails.org/active_record_validations.html#uniqueness
```suggestion
    raise Exceptions::Conflict, '이미 가입된 이메일입니다' if User.exists?(email: params[:email])
```

2022-10-05 04:58 UTC, 51326 commented on app/controllers/application_controller.rb
> +    render json: { message: '로그인이 필요합니다' }, status: Exceptions::Unauthorized.http_status if current_user.blank?
`Exceptions::Unauthorized` 클래스도 `rescue_from`으로 정의가 되어 있으니 아래와 같이 바로 `raise` 시키면 될 것 같네요.

```suggestion
    raise Exceptions::Unauthorized, '로그인이 필요합니다' if current_user.blank?
```

2022-10-05 04:58 UTC, 51326 commented on app/controllers/application_controller.rb
> +    exception_handler e, :bad_request
에러 클래스별로 http_status 메소드를 구현해두셨던데 그걸 사용하면 좋을 것 같네요
```suggestion
    exception_handler e, e.class.http_status
```

2022-10-05 04:58 UTC, 51326 commented on app/controllers/users_controller.rb
> +    render json: { message: '아이디와 비밀번호를 확인해주세요' }, status: Exceptions::BadRequest.http_status
```suggestion
    raise Exceptions::BadRequest, '아이디와 비밀번호를 확인해주세요'
```

2022-10-05 04:58 UTC, 51326 commented on app/models/taxi_request.rb
> +
status에 대한 validate도 추가해주세요.
https://guides.rubyonrails.org/active_record_validations.html#inclusion

2022-10-05 04:58 UTC, 51326 commented on app/models/user/driver.rb
> +    has_many :taxi_requests
Drive / Passenger 공통으로 가지고 있는것 같은데 User 모델에 정의하면 안될까요?

2022-10-05 04:58 UTC, 51326 commented on app/services/create_user_service.rb
> +                end
case문을 사용하지 않아도 되는 아래와 같은 패턴도 있습니다.

```suggestion
    USER_TYPES_CLASS = {
      'driver' => User::Driver,
      'passenger' => User::Passenger
    }
    ...
    user_type = USER_TYPES_CLASS[@params[:userType]]
```

2022-10-05 04:58 UTC, 51326 commented on app/services/create_user_service.rb
> +      status: @params[:status] || 'normal'
empty string 값인 경우에는 기본값이 사용되지 않기에 이러한 경우 `presence` 메소드를 사용해주세요.
```suggestion
      status: @params[:status].presence || 'normal'
```

2022-10-05 04:58 UTC, 51326 commented on app/services/current_user_provider.rb
> +  CURRENT_USER_KEY ||= '_CURRENT_USER_KEY'
혹시 이렇게 지정한 이유가 뭔가요?

2022-10-05 04:58 UTC, 51326 commented on app/services/current_user_provider.rb
> +    current_user = User.where(token: token_from_header).take if token_valid?
이런경우 take 대신 바로 find_by를 사용해주세요.
```suggestion
    current_user = User.find_by(token: token_from_header)if token_valid?
```

2022-10-05 05:04 UTC, travelingaries commented on app/controllers/application_controller.rb
> +  end
[cf0fb23](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/cf0fb23155c38a25082fa0ce8e2e32d9b9f2050b)에서 제안주신대로 수정했습니다~

2022-10-05 05:07 UTC, travelingaries commented on app/controllers/concerns/user_type_resolver.rb
> +end
앗 [2d0d104](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/2d0d104917db26aefb1228b2dfb3c352839ff730)에서 수정했습니다🙆‍♂️

2022-10-05 05:10 UTC, travelingaries commented on app/controllers/taxi_requests_controller.rb
> +  end
[05cb972](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/05cb972339015c1fb40712df09c65be54b3de426)에서 설명주신 대로 before_action들 한 줄로 수정했습니다~

2022-10-05 05:19 UTC, travelingaries commented on app/models/user/driver.rb
> +    has_many :taxi_requests
[TaxiRequest 모델에 passenger, driver association을 User::Passenger, User::Driver에 대해 정의해두어서](https://github.com/travelingaries/taxi-dispatch-backend-api/blob/05cb972339015c1fb40712df09c65be54b3de426/app/models/taxi_request.rb#L4-L4), User모델에 taxi_requests has_many association을 두면 `User::Passenger.first.taxi_requests`이 안 돌아가더라고요..

2022-10-05 05:23 UTC, travelingaries commented on app/services/current_user_provider.rb
> +  CURRENT_USER_KEY ||= '_CURRENT_USER_KEY'
`_CURRENT_USER_KEY` 값에 대해서 여쭈신게 맞으실까요?? 큰 이유가 있던건 아니고, 다른 env 키들과 겹치지 않으면 된다고 생각했어요. 혹시 적절하지 않을까요?

2022-10-05 05:41 UTC, travelingaries commented on app/services/current_user_provider.rb
> +    current_user = User.where(token: token_from_header).take if token_valid?
[6ab6544](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/6ab6544dc200974330b37ac59f3005631008cbf6)에서 수정했습니다 🙆‍♂️

2022-10-05 05:45 UTC, travelingaries commented on app/services/create_user_service.rb
> +      status: @params[:status] || 'normal'
[8ac2153](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/8ac21532f29b96b40aa34cc6eb76f13128abeffd)에서 위 방법으로 수정했습니다 🙆‍♂️

2022-10-05 08:07 UTC, travelingaries commented on app/services/current_user_provider.rb
> +  CURRENT_USER_KEY ||= '_CURRENT_USER_KEY'
[2e9b84a](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/2e9b84a114357536c61b9bd7a31ae4ec853f0fc3)에서 =로 선언만 하도록 수정했습니다 🙆‍♂️

2022-10-05 08:08 UTC, travelingaries commented on app/services/create_user_service.rb
> +                end
요거 재사용 가능성이 있다고 생각들어서 User 모델에 구현하는 방법으로 [9f9ac24](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/9f9ac24102f3e27ec4faf23c52b186901261ad9a)에서 수정했어요~

2022-10-05 08:22 UTC, travelingaries commented on app/models/taxi_request.rb
> +
`validates :status, inclusion: { in: statuses.keys }` 없이도 [enum 선언만 해도 그 안에 있는 값들만 허용되도록 validate하는 듯 한데](https://www.bigbinary.com/books/learn-rubyonrails-book/using-enums-in-rails), 혹시 다른 거에 대한 validation이 추가로 필요할까요?

2022-10-06 01:46 UTC, travelingaries commented on app/controllers/users_controller.rb
> +    raise Exceptions::BadRequest, '올바른 사용자 타입을 입력해주세요' unless valid_user_type?(params[:userType])
[f63a93e](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/f63a93e1372d1fec0a55776eefac69a97983fb96)에서 sign_up_params에서 raise 안 하도록 플로우 수정했습니다 🙆

2022-10-06 01:49 UTC, travelingaries commented on app/controllers/users_controller.rb
> +  end
[f63a93e](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/f63a93e1372d1fec0a55776eefac69a97983fb96) 작업하면서 같이 변경했습니다!

2022-10-06 04:12 UTC, travelingaries commented on app/controllers/users_controller.rb
> +    raise Exceptions::Conflict, '이미 가입된 이메일입니다' if User.find_by(email: params[:email]).present?
모델에 uniqueness validation 추가하고, 생성 시 이 validation에 걸리면 controller에서 에러 raise하도록 [291b4ca](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/291b4cabe1e033d151f7dabfe86ff0be232012ba)에서 플로우 수정했습니다 🙆‍♂️ 
혹시 생각하고 있으셨던 로직이 요게 아니라면 알려주세요

2022-10-06 04:25 UTC, travelingaries commented on app/controllers/application_controller.rb
> +    exception_handler e, :bad_request
[ef05ddc](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/ef05ddc30734f86914835d18edc1bc045454d8a3)에서 수정했습니다

2022-10-06 08:41 UTC, travelingaries commented on spec/controllers/taxi_requests_controller_spec.rb
> +        before(:each) do
[11b0788](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/11b07882e4e04b07fb7e8e187a44ff1ad4fcbcf6)에서 each 생략하도록 수정했습니다 🙆‍♂️

2022-10-06 10:13 UTC, 51326 requested changes
코멘트 추가해두었습니다. 수고하셨습니다!
궁금한 사항이나 논의해보고 싶으신 내용이 있으면 언제든 말씀해주세요!!

2022-10-06 10:13 UTC, 51326 commented on spec/controllers/users_controller_spec.rb
> +        expect(subject['accessToken']).to_not be_nil
여기도 API 응답값을 Serializer 한것과 비교해주세요.

2022-10-06 10:13 UTC, 51326 commented on spec/factories/user.rb
> +    password_digest   { Faker::Internet.password }
```suggestion
    password { Faker::Internet.password }
```

2022-10-06 10:13 UTC, 51326 commented on spec/models/user_spec.rb
> +  let!(:user) { create(:user) }
User 모델에 정의된 validate도 테스트 추가해주세세요.
Class method나 public method도 모두 테스트 코드를 작성하고 있습니다.

2022-10-06 10:13 UTC, 51326 commented on spec/models/user_spec.rb
> +    end
이건 사실상 Rails에서 제공하는 `has_secure_password`에서 담당하는 기능이라 테스트를 작성하지 않아도 될 것 같습니다.

2022-10-07 01:00 UTC, travelingaries commented on app/controllers/taxi_requests_controller.rb
> +    raise Exceptions::BadRequest, '주소는 100자 이하로 입력해주세요'
요거 아까 허들로 상의된 형태로 수정하려고 알아보다가,
`validates :address, length: { maximum: 100, message: "hi" }`
이렇게 message를 지정할 순 있지만, controller에서 e.message를 하면
`Validation failed: Address hi`
이렇게 나오길래, 파싱해서 사용하기도 애매할 듯 해서 다시 원상복구했습니다 🥲

현 상태
```
# taxi_requests_controller.rb
rescue ActiveRecord::RecordInvalid, ActionController::ParameterMissing
    raise Exceptions::BadRequest, '주소는 100자 이하로 입력해주세요'
  end

...

# taxi_request.rb
validates :address, length: { maximum: 100 }
```

2022-10-07 01:19 UTC, travelingaries commented on spec/controllers/taxi_requests_controller_spec.rb
> +        end
설명해주신 내용 바탕으로 [d970059](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/d9700590e719a2b04565e4dcdea0d2603375d7a2) 에서 수정했습니다 🙆‍♂️

2022-10-07 01:21 UTC, travelingaries commented on spec/controllers/taxi_requests_controller_spec.rb
> +      end
[50b9e6f](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/50b9e6fc4a3b5d7304dd22b96cdc1493b8fd9f4e)에서 수정했습니다~

2022-10-07 02:26 UTC, travelingaries commented on spec/controllers/taxi_requests_controller_spec.rb
> +  context '유효한 토큰이 있는 기사인 경우' do
[56552f9](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/56552f926e91798b7e90ff5a910a90d215167dec)에서 describe가 최상위로 오도록 수정해두었습니다!

2022-10-07 07:25 UTC, travelingaries commented on spec/controllers/taxi_requests_controller_spec.rb
> +        end
[describe가 최상위에 오도록 테스트코드 리팩토링하면서](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/56552f926e91798b7e90ff5a910a90d215167dec) 같이 수정했습니다 🙆‍♂️ 
명확히 통제된 상황으로, let으로 갯수 세도록 하기 추후 참고하겠습니다, 감사합니다~

2022-10-07 07:41 UTC, travelingaries commented on spec/controllers/users_controller_spec.rb
> +      end
응답 전체를 확인하도록 [fa88660](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/fa886601c0da2180f3051d8aa6a15d708a9f48d2)에서 수정했습니다~

2022-10-07 07:42 UTC, travelingaries commented on spec/controllers/users_controller_spec.rb
> +      end
이것도 [77e9871](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/77e9871a00db7c456ec20efefc205bf5516e6b14)에서 수정했습니다 🙆‍♂️

2022-10-07 07:57 UTC, travelingaries commented on spec/controllers/users_controller_spec.rb
> +        expect(subject['accessToken']).to_not be_nil
[cb3c31a](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/cb3c31a6c9513b9b37a9fcbb200d6653f2363572)에서 Serializer 사용하도록 수정하고,
[0edf722](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/0edf722207370235c378a666dee340dda3e5eec6)에서 응답 전체를 serialize한 것과 비교하도록 수정했습니다 🙆‍♂️

2022-10-07 07:59 UTC, travelingaries commented on spec/factories/user.rb
> +    password_digest   { Faker::Internet.password }
[2145ee4](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/2145ee4c662456abe3f0d8a243cd177231916bcb)에서 위와 같이 수정했습니다 (indent만 다르게)

2022-10-07 08:59 UTC, travelingaries commented on spec/models/user_spec.rb
> +  let!(:user) { create(:user) }
[57b6c6a](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/57b6c6afb802792c712be5f6d9dc42a716604c5d)에서 validation 테스트코드 추가했습니다

2022-10-07 09:01 UTC, travelingaries commented on spec/models/user_spec.rb
> +    end
[3416357](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/1/commits/341635785b912f1e157b64929a252db61787484f)에서 제거했습니다 🙆‍♂️

2022-10-11 02:21 UTC, merged

2022-10-12 01:20 UTC, 51326 commented on app/controllers/taxi_requests_controller.rb
> +    raise Exceptions::BadRequest, '주소는 100자 이하로 입력해주세요'
locale 파일에서 에러 메시지 포맷을 지정해줄 수 있습니다. `config/locales/*.yml `

```yaml
  errors:
    format: "%{message}"
```

2022-10-12 02:49 UTC, travelingaries commented on app/controllers/taxi_requests_controller.rb
> +    raise Exceptions::BadRequest, '주소는 100자 이하로 입력해주세요'
@51326 [PR#3](https://github.com/travelingaries/taxi-dispatch-backend-api/pull/3)에서 수정해보았습니다